[book]
authors = ["Nadai2010"]
language = "es"
multilingual = false
src = "src"
title = "Escalabilidad - Fundamentales"


[preprocessor.gettext]
after = ["links"]

[output.html.fold]
enable = true
level = 0
